import React, { useEffect } from "react";
import { bkslog, davaoseal } from "../../../assets/images";
import Thead from "./table/Thead";
import Tbody from "./table/Tbody";
import moment from "moment";
import "../../../assets/css/reports/totalapproverequest.css";

function PrintPageApprove({ data, fromDate, toDate, status, generatedBy }) {
  useEffect(() => {
    window.print();
  }, []);
  return (
    <>
      {/* Header */}
      <div className="print__request-header">
        <div className="print__request-header__left">
          <img src={bkslog} alt="logo" />
        </div>
        <div className="print__request-header__center">
          <p>Republic of the Philippines</p>
          <p>CITY OF DAVAO</p>
          <p>
            Barangay <span>BANKAS HEIGHTS</span>
          </p>
          <p>Toril District</p>
          <p>OFFICE OF THE SANGGUNIANG BARANGAY</p>
        </div>

        <div className="print__request-header__right">
          <img src={davaoseal} alt="logo" />
        </div>
      </div>
      {/* Report header */}
      <div className="print__approve-reports__body">
        <div className="print__approve-reports__body-left">
          <p>{status} Request Reports</p>
          <p>Dates</p>
          <p>From : {moment(fromDate).format("ll")}</p>
          <p>To : {moment(toDate).format("ll")}</p>
        </div>
        <div className="print__approve-reports__body-right">
          <p>Generated by : {generatedBy}</p>
          <p>Date : {moment(new Date()).format("ll")}</p>
        </div>
      </div>
      {/* Table */}
      <table>
        <Thead />
        <Tbody data={data} />
      </table>
    </>
  );
}

export default PrintPageApprove;
