export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SET_USER = "SET_USER";
export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_BARANGAYIMAGES = "SET_BARANGAYIMAGES";
export const SET_SETTINGS = "SET_SETTINGS";
